### ISSUE TITLE
Marketplace not responsive after latest update

### ISSUE THREAD

**Issue by Plueres** [spicetify/spicetify-marketplace#352]
### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.97.962.g24733a46
- Spicetify version: 2.14.0
```

### 📝 Description

When clicking the marketplace it sends me to a page where it says something went wrong along with other pages clicked on after that. This also happens when clicking on apps like lyrics+ or new releases.

### 📸 Screenshots
![image](https://user-images.githubusercontent.com/71077562/198217777-f64dc644-3c50-4c53-a045-980b6f904a24.png)

**Comment by kyrie25** [comment]
Resolved via spicetify/spicetify-cli#1996. Wait for the next CLI release.

**Comment by Plueres** [comment]
I already installed the newest commit, but it still doesn't work for me. Does the spicetify version number change normally?

**Comment by kyrie25** [comment]
> I already installed the newest commit, but it still doesn't work for me. Does the spicetify version number change normally?

**Wait** for the next **CLI** release.

**Comment by Plueres** [comment]
Alright
